## 
## Copyright 2021 Datum Technology Corporation
## SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
## 
## Licensed under the Solderpad Hardware License v 2.1 (the "License"); you may
## not use this file except in compliance with the License, or, at your option,
## the Apache License version 2.0. You may obtain a copy of the License at
## 
##     https://solderpad.org/licenses/SHL-2.1/
## 
## Unless required by applicable law or agreed to in writing, any work
## distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
## WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
## License for the specific language governing permissions and limitations
## under the License.
## 


## README
# This is a sample configuration file for the moore.io platform
# Although it differs in its language, it serves the same purpose as npm's .npmrc files and follow the same hierarchy: https://docs.npmjs.com/cli/v6/configuring-npm/npmrc#files
# This is essentially a data store used by various mio commands to determine their behavior



title = "Moore.io ARM Project Configuration"                                                       # Standard for toml files -- don't care from mio standpoint

[ip]
default-ip = ""

[vip]
default-vip = ""

[lint]
default-linters = [ { name = 'verilator' , version = '^' } ]

[synthesis]
default-synthesizers = [ { name = 'vivado' , version = '^' } ]


[simulation]
preffered-simulators = [ { name = "xilinx", version = "^" } ]
default-test-bench = ""
default-test = ""


[[version-control]]
type = "git"
url = "https://github.com/Datum-Technology-Corporation/mio_arm"
user-name = "peon"
password = "3700adf1f25fab8202c1343c4b0b4e3fec706d57cad574086467b8b3ddf273ec"


[[scheduling]]
type = "grid"
hosts = ["grid1.datumint.com"]
user-name = "peon"
password = "3700adf1f25fab8202c1343c4b0b4e3fec706d57cad574086467b8b3ddf273ec"
default-queue = "default"
default-priority = "medium"


[[ci]]
type = "jenkins"
url = "http://datumint.com/ci/jenkins/mio_arm"
user-name = "admin"
password = "3700adf1f25fab8202c1343c4b0b4e3fec706d57cad574086467b8b3ddf273ec"
